## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
#  - nightly
notifications:
  email: false
git:
  depth: 99999999

# Required for HDF5 to work on Linux. 
addons:
  apt:
    packages:
      - hdf5-tools

after_success:
  # push coverage results to Coveralls and Codecov. 
  - julia -e 'cd(Pkg.dir("IndustrialProcessFlexibilisation")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
